import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import { getSession } from "@/auth";
import AuthProvider from "./components/AuthProvider";
import { createTheme, MantineProvider } from "@mantine/core";
import "@mantine/core/styles.css";
const montserrat = Montserrat({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const theme = createTheme({
  // primaryColor: "thera-green", // Custom color name
  // colors: {
  //   "thera-green": [
  //     "#c2e2df", // Lightest shade
  //     "#68a9b0",
  //     "#187c8f", // Base color (primary shade)
  //     "#104f5e",
  //     "#0e3c4c", // Darkest shade
  //     "#0b2e3a",
  //     "#09262f",
  //     "#071e24",
  //     "#05171a",
  //     "#030f10",
  //   ],
  // },
  fontFamily: montserrat.style.fontFamily, // Ensure body text uses Montserrat
  headings: {
    fontFamily: montserrat.style.fontFamily, // Ensure headings use Montserrat
  },
  autoContrast: true,
});
export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getSession();
  return (
    <html lang="en">
      <body className={` antialiased`}>
        <AuthProvider session={session}>
          <MantineProvider theme={theme}>{children}</MantineProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
